name: CI

on:
  push:
    paths-ignore:
      - '**/README.md'

  workflow_dispatch:

jobs:
  build:
    name: flutter build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.7
      - name: Get Dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
    #   - name: Testing
    #     run: flutter test